const LEGAL_POLICY_TITLE = 'Legal Policy & Terms of Use';

const LEGAL_POLICY_SECTIONS = [
  {
    heading: '⚠️  Beta Testing Notice',
    body:
      'Optimized is currently operating as a closed beta application. This version of the app is provided for testing and evaluation purposes only. Features, data structures, and policies are subject to change without notice. By using this beta version you acknowledge that:\n\n' +
      '• The app may contain bugs, errors, or incomplete features.\n' +
      '• Your data may be reset, migrated, or deleted between beta versions.\n' +
      '• The beta period is temporary. When the official release launches, you will be given the opportunity to export your data before this instance is retired.\n' +
      '• No warranty of service continuity is made for the beta period.',
  },
  {
    heading: '1. Acceptance of Terms',
    body:
      'By creating an account or using Optimized ("the App", "the Service"), you confirm that you have read, understood, and agree to be bound by these Terms. If you do not agree, you must not use the App.\n\n' +
      'These Terms constitute a legally binding agreement between you ("User", "you") and the developer of Optimized ("we", "us", "our"). Your continued use of the App following any update to these Terms constitutes acceptance of the revised Terms.',
  },
  {
    heading: '2. Eligibility & Age Restriction',
    body:
      'You must be at least 16 years of age to create an account and use the App. By registering, you represent and warrant that you meet this minimum age requirement.\n\n' +
      'Users under 18 should obtain consent from a parent or legal guardian before using the App or engaging in any physical exercise programme influenced by its content.',
  },
  {
    heading: '3. Physical Exercise — Assumption of Risk',
    body:
      'Physical exercise carries an inherent risk of injury, illness, or death. By using the App you acknowledge and voluntarily assume all risks associated with physical activity, including but not limited to:\n\n' +
      '• Musculoskeletal injury (strains, sprains, fractures).\n' +
      '• Cardiovascular events during or after exercise.\n' +
      '• Overtraining, fatigue, or rhabdomyolysis.\n' +
      '• Injury from improper exercise technique.\n\n' +
      'You are solely responsible for ensuring that you are physically capable of performing any exercise logged or suggested within the App. We strongly recommend consulting a qualified medical professional before beginning any new exercise programme, particularly if you have a pre-existing medical condition, injury, or have been sedentary.',
  },
  {
    heading: '4. No Medical Advice',
    body:
      'The App and all content within it — including workout logs, volume metrics, body part breakdowns, and any other data visualisations — are provided for general informational and motivational purposes only.\n\n' +
      'Nothing in the App constitutes medical advice, clinical assessment, diagnosis, treatment recommendation, or a substitute for advice from a licensed physician, physiotherapist, dietitian, or other qualified healthcare professional.\n\n' +
      'Do not use the App\'s data to self-diagnose injury, plan rehabilitation, manage a medical condition, or make decisions about medication or surgery. Always seek professional medical guidance for health concerns.',
  },
  {
    heading: '5. Fitness Data & Muscle Activation Disclaimer',
    body:
      'Muscle group activation percentages and body part breakdown figures displayed in the App are algorithmic estimates generated by a computational model based on peer-reviewed exercise science literature. They are adjusted using your self-reported fitness level to approximate general recruitment patterns.\n\n' +
      'These estimates:\n\n' +
      '• Are NOT electromyography (EMG) measurements or clinically validated data.\n' +
      '• Do NOT reflect your personal anatomy, limb proportions, injury history, or neurological profile.\n' +
      '• May not accurately represent which muscles you personally activate during any given exercise.\n' +
      '• Are intended as a general visual reference only — not a precise physiological report.\n\n' +
      'Individual muscle recruitment varies significantly between people. We make no warranty, expressed or implied, regarding the accuracy of these estimates for any specific individual. Do not rely on this data to diagnose injury, identify muscular imbalances, or plan clinical rehabilitation.',
  },
  {
    heading: '6. Data Collection',
    body:
      'When you create an account or use the App, we collect:\n\n' +
      '• Account identifiers: email address, chosen username.\n' +
      '• Profile data: age, gender, bodyweight, height, fitness level.\n' +
      '• Training data: workout logs, exercises, sets, reps, weights, duration, comments.\n' +
      '• App preferences: theme, language, unit of measurement, avatar selection.\n' +
      '• Usage metadata: timestamps of actions, session counts.\n\n' +
      'Data is stored securely using Firebase (Google Cloud) infrastructure. We do not sell your personal data to third parties.',
  },
  {
    heading: '7. Data Usage & Analytics',
    body:
      'Data you provide may be used for:\n\n' +
      '• Operating and personalising the Service.\n' +
      '• Product improvement, quality assurance, and feature development.\n' +
      '• Aggregate, anonymised analytics to understand usage patterns.\n' +
      '• Validating and refining algorithmic models (e.g., fitness-level adjustment formulas) using anonymised, aggregated data only.\n\n' +
      'We will never use individually identifiable training data for any purpose beyond operating the Service without your explicit consent.',
  },
  {
    heading: '8. Account Responsibility & Security',
    body:
      'You are responsible for:\n\n' +
      '• Providing accurate and truthful account information.\n' +
      '• Maintaining the confidentiality of your login credentials.\n' +
      '• All activity that occurs under your account.\n' +
      '• Notifying us immediately if you suspect unauthorised access.\n\n' +
      'We reserve the right to suspend or terminate accounts that provide false information, engage in abusive behaviour, or violate these Terms.',
  },
  {
    heading: '9. Intellectual Property',
    body:
      'All content, code, design, algorithms, and data structures within the App are the exclusive intellectual property of the developer unless otherwise stated. You are granted a limited, non-transferable, revocable licence to use the App for personal, non-commercial purposes only.\n\n' +
      'You may not copy, reproduce, reverse-engineer, distribute, or create derivative works from any part of the App without prior written permission.',
  },
  {
    heading: '10. Third-Party Services',
    body:
      'The App uses Firebase by Google for authentication, data storage, and infrastructure. Your use of the App is also subject to Google\'s Privacy Policy and Firebase Terms of Service. We are not responsible for the practices of third-party service providers beyond our reasonable control.',
  },
  {
    heading: '11. Service Availability & Changes',
    body:
      'We do not guarantee uninterrupted access to the App. The Service may be modified, suspended, or discontinued at any time, including at the conclusion of the beta period, without prior notice.\n\n' +
      'We reserve the right to update these Terms at any time. Material changes will be communicated within the App where reasonably practicable. Continued use after notification constitutes acceptance.',
  },
  {
    heading: '12. Limitation of Liability',
    body:
      'To the fullest extent permitted by applicable law, we shall not be liable for any direct, indirect, incidental, consequential, special, or punitive damages arising from:\n\n' +
      '• Your use of or inability to use the App.\n' +
      '• Physical injury or health consequences arising from exercise activities.\n' +
      '• Reliance on any data, estimates, or information provided by the App.\n' +
      '• Loss of data, account access, or service interruption.\n' +
      '• Errors, inaccuracies, or omissions in any App content.\n\n' +
      'In jurisdictions that do not allow limitation of liability for personal injury, the above may not apply to you.',
  },
  {
    heading: '13. Indemnification',
    body:
      'You agree to indemnify, defend, and hold harmless the developer and any associated individuals from and against any claims, damages, obligations, losses, liabilities, costs, or expenses (including legal fees) arising from:\n\n' +
      '• Your use of the App.\n' +
      '• Your violation of these Terms.\n' +
      '• Your violation of any third-party right, including intellectual property or privacy rights.\n' +
      '• Any injury or harm caused to yourself or others as a result of physical activities undertaken in connection with the App.',
  },
  {
    heading: '14. Termination',
    body:
      'You may delete your account at any time from within the App. Upon deletion, your personal data and training records will be permanently removed from our systems.\n\n' +
      'We reserve the right to terminate or suspend your account at our discretion, without notice, for conduct that violates these Terms or is otherwise harmful to users, third parties, or the integrity of the Service.',
  },
  {
    heading: '15. Governing Law',
    body:
      'These Terms shall be governed by and construed in accordance with applicable law. Any disputes arising from these Terms or your use of the App should first be raised directly with us through the in-app contact options so that we may attempt to resolve them informally before any formal proceedings.',
  },
  {
    heading: '16. Contact',
    body:
      'For questions, concerns, or disputes regarding this policy or the App, please use the Contact Us option available in the app settings. We will endeavour to respond within a reasonable timeframe.',
  },
];

const LEGAL_POLICY_ACCEPTANCE_LABEL =
  'I have read and accept the Legal Policy & Terms of Use, including the Beta Testing Notice, Physical Exercise Assumption of Risk, and all other clauses.';

export { LEGAL_POLICY_ACCEPTANCE_LABEL, LEGAL_POLICY_SECTIONS, LEGAL_POLICY_TITLE };
